### PR TITLE
Remove broken Twitter widget

### LINKED ISSUE #738: Tweet sidebar looks garish
image

The twitter sidebar interferes with the readability of PEPs and other pages, and doesn't add much value. 

If we're going to keep it on pages besides the homepage, can we at least not show it on static docs?

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/python/pythondotorg/issues/738.

The Twitter widget is broken, let's remove it:

image

https://www.python.org/about/gettingstarted/

### CODE REVIEW

**Comment by hugovk** [comment]
I edited `style.css` by hand.

Then I read the docs and installed the sass tools to run `sass --compass --scss -I $(dirname $(dirname $(gem which susy))) --trace --watch sass/style.scss:sass/style.css`, but it changed a lot more than what was removed here, so I didn't commit it.

**Comment by malemburg** [comment]
LGTM. The ReadTheDocs failure should go away with #2328

**Review by willingc — APPROVED** [review]
LGTM @hugovk

**Comment by malemburg** [comment]
I didn't know how to rerun the ReadTheDocs part of the checks, so just merged, since the main checks were fine.

**Comment by malemburg** [comment]
Thanks, @hugovk 

These changes will now need to be merged into the release branch to make them go live.

**Comment by malemburg** [comment]
Let's wait for staging to pick up the changes first: https://staging.python.org/about/gettingstarted/

**Comment by malemburg** [comment]
All good. Created #2330 to make this go live.

**Pull request merged**
