### PR TITLE
Design/new font body copy

### PR DESCRIPTION
**Pull request by jhogue**
Changed the body font from default Arial to something prettier. Adjusted sizes and general styles accordingly. Replaced Flux when it was appearing as yellow or white over dark blue or in large strings of text. Small associated edits to files other than CSS.

### CODE REVIEW

**Comment by frankwiles** [comment]
Was trying to merge this today, but got really confused on what was the intended result at the end.  Can you sync up with master on it and merge?

**Comment by jhogue** [comment]
Let me fire this up in a VM to double check, but the merge is complete.

**Comment by jhogue** [comment]
LGTM. Ready to close after your review.

**Comment by frankwiles** [comment]
I'm still getting conflicts on this one.  You want to just go ahead and merge and verify them?

**Comment by jhogue** [comment]
Merged and verified. I re-ran Compass on the SCSS, and checked the styles
in a VM. I'll wait to do the merge on the other one until this branch is
part of Master. That seems to be the way to go.

These merges are pretty messy. Once the base code is in Master, I should do
another review before going to the preview server.

On Wed, Jul 24, 2013 at 3:51 PM, Frank Wiles notifications@github.comwrote:

> I'm still getting conflicts on this one. You want to just go ahead and
> merge and verify them?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/proevo/pythondotorg/pull/29#issuecomment-21511282
> .

## 

_J. Hogue_: Design Director at Project Evolution
t: 888.456.0467 | c: 401.831.1963

**Comment by frankwiles** [comment]
Cool I just merged it.  Go ahead and merge this one when you get it ready
and just make master happy.  No one else is really doing any active dev
today that will conflict with you so go for it!

## 

Frank Wiles
Revolution Systems | http://www.revsys.com/
frank@revsys.com   | (800) 647-6298

**Pull request merged**
