### PR TITLE
Update https://pypi.python.org -> https://pypi.org

### LINKED ISSUE #1593: Update "pypi.python.org" to "pypi.org" on Download page
**To Reproduce**

"Other Useful Items" within https://www.python.org/downloads/ says:
> Looking for 3rd party Python modules? The [Package Index](http://pypi.python.org/pypi) has many of them.

pointing to http://pypi.python.org/pypi , the old PyPI site.

**Expected behavior**
As of 2018, PyPI has moved to pypi.org; it would be nice to point directly there instead of causing a redirect.

**Additional info**
I seem to have the ability to edit the Downloads page within the CMS, but it seemed to have obsolete info within the page text, so I assume that's not the right place to edit this page's text.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/python/pythondotorg/issues/1593.

The old link is found in three places:

1. https://www.python.org/downloads/ -> "Other Useful Items" -> "Looking for 3rd party Python modules? The Package Index has many of them."

2. https://www.python.org/about/ -> "The Python Package Index (PyPI) hosts thousands of third-party modules for Python."

3. Top of both pages -> "PyPI" in header menu

---

Not in code so not part of this PR. Are these in the database?

* https://www.python.org/about/apps/

  * "The Python Package Index lists thousands of third party modules for Python."
  * "And the Package Index has yet more libraries: ..."

### CODE REVIEW

**Review by brainwane — APPROVED** [review]
Looks good to me from a content standpoint! Thanks!

**Comment by brainwane** [comment]
> Not in code so not part of this PR. Are these in the database?
> 
>     * https://www.python.org/about/apps/
>       
>       * "The Python Package Index lists thousands of third party modules for Python."
>       * "And the Package Index has yet more libraries: ..."

Thanks @hugovk! I've fixed these within the CMS.

**Review by berkerpeksag — APPROVED** [review]
LGTM!

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
