### PR TITLE
removed access_guest from sitetree_menus.json

### PR DESCRIPTION
**Pull request by originalankur**
I have corrected the sitetree_menus.json fixture by removing the access_guest.

### CODE REVIEW

**Comment by benjaminp** [comment]
How does this correct it?

**Comment by originalankur** [comment]
find ./fixtures -name "_.json" -exec python3.3m manage.py loaddata {} \;
Installed 31 object(s) from 1 fixture(s)
Installed 15 object(s) from 1 fixture(s)
Installed 2 object(s) from 1 fixture(s)
Installed 13 object(s) from 1 fixture(s)
DeserializationError: Problem installing fixture './fixtures/sitetree_menus.json': TreeItem has no field named 'access_guest'
Installed 4 object(s) from 1 fixture(s)
Installed 5 object(s) from 1 fixture(s)
Installed 11 object(s) from 1 fixture(s)
Installed 10 object(s) from 1 fixture(s)
Installed 4 object(s) from 1 fixture(s)
(env) go@goprogramming:~/pythondotorg$ vim ./fixtures/sitetree_menus.json 
(env) go@goprogramming:~/pythondotorg$ vim ./fixtures/sitetree_menus.json 
(env) go@goprogramming:~/pythondotorg$ find ./fixtures -name "_.json" -exec python3.3m manage.py loaddata {} \;
Installed 31 object(s) from 1 fixture(s)
Installed 15 object(s) from 1 fixture(s)
Installed 2 object(s) from 1 fixture(s)
Installed 13 object(s) from 1 fixture(s)
Installed 90 object(s) from 1 fixture(s)
Installed 4 object(s) from 1 fixture(s)
Installed 5 object(s) from 1 fixture(s)
Installed 11 object(s) from 1 fixture(s)
Installed 10 object(s) from 1 fixture(s)
Installed 4 object(s) from 1 fixture(s)

**Comment by originalankur** [comment]
https://github.com/idlesign/django-sitetree/blob/master/sitetree/models.py TreeItem is inheriting TreeItemBase which has access_guest I am not sure what's missing. I check the version of package. It matches the requirements.txt ...

**Comment by lepot311** [comment]
I will take another look tomorrow

**Comment by berkerpeksag** [comment]
Looks like this was already fixed in https://github.com/python/pythondotorg/commit/664eba4b5d3990d4102fab05476afa4d6f1283b6.

**Pull request closed without merging**
