### PR TITLE
Fix for Can't find Python docker images #2010 and Linted Files to remove inconsistent formatting.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Fix for Can't find Python docker images #2010 and Linted Files to remove inconsistent formatting.

### CODE REVIEW

**Comment by Harry-Hopkinson** [comment]
The code builds fine so the changes are ready for review.

**Comment by Mariatta** [comment]
Can you not include any of the formatting changes in the PR? It's hard to review, I couldn't figure out where exactly was the fix for the docker image.

**Comment by Harry-Hopkinson** [comment]
Sure

**Comment by Harry-Hopkinson** [comment]
I am opening the pull request elsewhere to remove the linting issues.

**Pull request closed without merging**
