### PR TITLE
Remove link to facebook and add LinkedIn in the Python.org socialize menu

### LINKED ISSUE #2325: Remove link to facebook and add LinkedIn in the Python.org socialize menu
Along the same lines as issue #2322 I would suggest making two more small changes to the Socialize menu:
- Remove the Facebook link, the last post being almost 10 years ago (March 2014) it is effectively dormant and doesn't make sense to send folks there, imo.  
- Add a link to the [PSF LinkedIn page](https://www.linkedin.com/company/thepsf), which is active and has a significant following (127k followers).

### PR DESCRIPTION
**Pull request by mlcohen**
Updated the socialize menu:

- Removed Facebook link
- Added Linkedin link

Details

- Updated the social menu in the base.html template
- Updated the Pythonicon font set to include the LinkedIn icon
- Updated various Sass and CSS files to accommodate the new LinkedIn icon

Note that the Linkedin icon SVG was taken from [Wikipedia Commons](https://commons.wikimedia.org/wiki/File:LinkedIn_icon.svg). The official [branded](https://brand.linkedin.com/downloads) Linkedin icon is only offered as a PNG.

Resolves https://github.com/python/pythondotorg/issues/2325

## Before Update

Screenshot 2023-11-18 at 9 24 35 PM

## After Update

Screenshot 2023-11-18 at 9 23 27 PM

(screenshot taken from localhost)

### CODE REVIEW

**Comment by mlcohen** [comment]
Hmm, I'm not entirely sure what to do about the Read the Docs build failure.

> Problem in your project's configuration. No default configuration file found at repository's root.

Nothing in my PR touches the docs. Anyone know what the issue is?

**Comment by hugovk** [comment]
Don't worry about the RTD failure, it's started happening for all builds:

https://readthedocs.org/projects/pythondotorg/builds/

Here's the fix:

https://blog.readthedocs.com/migrate-configuration-v2/

And I've suggested an improved error message at RTD:

https://github.com/readthedocs/readthedocs.org/pull/10910

Edit: See https://github.com/python/pythondotorg/pull/2328 to fix the RTD build.

**Review by hugovk — APPROVED** [review]
Tested locally, looks good. Thanks!

**Comment by hugovk** [comment]
I think this is ready for merge! 👍

**Comment by ewdurbin** [comment]
superseded by #2367

**Pull request closed without merging**
