### PR TITLE
Fix #225 - Add some useful help to the 404 page.

### LINKED ISSUE #225: Change the 404 page to include some useful help
Some examples:
- provide a direct link to the legacy version of the page
- mention/include the search box, possibly suggesting search terms based on the URL components
- list some high level entry points such as the documentation index, the PEP index, the PyPI package index

### PR DESCRIPTION
**Pull request by ronjouch**
- Provide a direct link to the legacy version of the same path.
- Mention the search box.
- List some high level entry points: documentation, pypi, downloads.

### CODE REVIEW

**Comment by ronjouch** [comment]
Just followed @malemburg suggestions from #225. This is my first patch on a django app so I hope I'm not doing anything horribly wrong; feedback welcome.

**Comment by berkerpeksag** [comment]
Looks good, thanks! I will test the patch locally and merge it.

**Comment by berkerpeksag** [comment]
Merged in https://github.com/python/pythondotorg/commit/6d73b791d895c518bf16f9779fe88ff9cb5cf49b. Thanks @ronjouch! :)

**Comment by ronjouch** [comment]
Yay, thanks mtlpython and @mlhamel for help on the initial setup.

**Comment by ronjouch** [comment]
@berkerpeksag thanks for the review :) . One unrelated question out of curiosity: I see you're ...
1. Sometimes merging using GitHub's PR features (thus generating an additional merge commit)...
2. ... and sometimes merge in a single commit using git's author/committer nuance.

I use GitHub Enterprise at work, and even though just clicking the green Merge button is convenient, I'm starting to dislike a lot these merge commits which pollute the history and don't add much to git's author/committer. Is this the reason you sometimes for option 2. ? Any other reason? What's your workflow?

**Comment by berkerpeksag** [comment]
Yes, I don't like merge commits either :)

I go with option 1 for typos, documentation fixes and trivial patches. I go with option 2 if I need to test the patch on my machine and/or make some trivial changes before committing it.

**Pull request closed without merging**
