### PR TITLE
Mod: update code sample to use variable `a_list` instead of `list`

### PR DESCRIPTION
**Pull request by yegle**
`list` is really not a good variable name in Python :-)

### CODE REVIEW

**Comment by benjaminp** [comment]
Probably this is superseded/complemented by #141?

**Comment by joncle** [comment]
I would argue that `sum` is also not a good name... if `list` is being renamed to `a_list`, then `sum` should be renamed to `total` (or similar). (Depending on outcome of #141).

**Comment by lepot311** [comment]
I agree with @gutworth that #141 addresses this.

**Comment by berkerpeksag** [comment]
Superseded by #526.

**Pull request closed without merging**
