### PR TITLE
Fix jobs/tests/test_models.py misusing `assertTrue`

### LINKED ISSUE #1986: Some tests misusing assertTrue for comparisons
`assertTrue` is not for comparing arguments, should use `assertEqual` for that.

The developer's intent of the test was to compare argument 1 with argument 2, which is not happening. Really what is happening is the test is passing because first argument is truthy. The correct method to use is assertEqual. [more details](https://codereview.doctor/features/python/best-practice/avoid-misusing-unittest-assert-true)

https://github.com/python/pythondotorg/blob/f25f22372ccb7fb6f98c2f00c58dad3bb19a9d73/jobs/tests/test_models.py#L79

I found this issue automatically, see other issues [here](https://codereview.doctor/python/pythondotorg)

### PR DESCRIPTION
**Pull request by code-review-doctor**
Fixes #1986

### CODE REVIEW

**Review by rbanffy — APPROVED** [review]
LGTM

**Review by rbanffy — APPROVED** [review]
Sorry. Not a full-time contributor. At least I had an approve button ;-)

**Review by ambv — APPROVED** [review]
This is a valid fix, and a straightforward change.

**Comment by hugovk** [comment]
Here's some others, found using https://github.com/isidentical/teyit.

`assert_` was removed in 3.12: https://docs.python.org/3/whatsnew/3.12.html#id3

```diff
diff --git a/downloads/tests/test_models.py b/downloads/tests/test_models.py
index f27e951..d31afae 100644
--- a/downloads/tests/test_models.py
+++ b/downloads/tests/test_models.py
@@ -82,8 +82,8 @@ class DownloadModelTests(BaseDownloadTests):
 
         release_38 = Release.objects.create(name='Python 3.8.0')
         self.assertFalse(release_38.is_version_at_least_3_9)
-        self.assert_(release_38.is_version_at_least_3_5)
+        self.assertTrue(release_38.is_version_at_least_3_5)
 
         release_310 = Release.objects.create(name='Python 3.10.0')
-        self.assert_(release_310.is_version_at_least_3_9)
-        self.assert_(release_310.is_version_at_least_3_5)
+        self.assertTrue(release_310.is_version_at_least_3_9)
+        self.assertTrue(release_310.is_version_at_least_3_5)
```

**Comment by JacobCoffee** [comment]
@hugovk these `assert_` bits i think will be cleaned up in #2535

**Review by JacobCoffee — APPROVED** [review]

**Comment by JacobCoffee** [comment]
will merge after #2520 settles

**Pull request merged**
