### PR TITLE
Only show sign in box in PSF pages.

### LINKED ISSUE #536: Move sign in dialog to the community page
As has been pointed out, "signing in" is completely unimportant when you want to download Python, browse the docs, or even contribute or participate in the community. It should be moved out of the top page and in a dedicated box in the community page, with a text explaining that it's totally optional even for contributing.

### PR DESCRIPTION
**Pull request by berkerpeksag**
Fixes #536.

### CODE REVIEW

**Comment by Mariatta** [comment]
I think this works and definitely agree that the sign in box should only appear where it needs to be.

My only concern is that this creates inconsistency with the placement of the search textbox. 
In most pages the search box will be more to the right of the page, whereas in the PSF page, where the sign in page is shown, it will be slightly to the left.

Perhaps not a big deal though, but then again maybe not my call.
Is there anyone who can provide input on this?

Thanks.

**Comment by berkerpeksag** [comment]
With this PR applied, screenshot of the homepage:

screenshot from 2017-08-10 23 01 34

Screenshoot of the PSF landing page:

screenshot from 2017-08-10 23 03 36

**Comment by MarkMangoba** [comment]
@berkerpeksag amazing looks so much cleaner.

**Comment by berkerpeksag** [comment]
I noticed a bug. I think we should still show "Your account" link in every page if user is already logged in:

screenshot from 2017-08-10 23 13 58

I've fixed it in the latest version of the PR.

**Pull request merged**
