### PR TITLE
Never show non-published Releases on the /downloads/ pages.

### LINKED ISSUE #162: Non-published releases offered for download on the "downloads" menu
The main "Downloads" menu appears to offer always the latest 3.x release, even when it's set to "not published" and "not show in download page" in the metadata.

### PR DESCRIPTION
**Pull request by birkenfeld**
Fixes #162.

### CODE REVIEW

**Comment by peterlandry** [comment]
Can you update the tests to match the code changes?

**Comment by birkenfeld** [comment]
Done.

**Comment by peterlandry** [comment]
Thanks. Fwiw, code looks good to me. I'm not qualified to comment on the behavior change.

**Comment by benjaminp** [comment]
We definitely want this.

**Pull request merged**
