### PR TITLE
Do not show information box if the job is already approved.

### PR DESCRIPTION
**Pull request by berkerpeksag**

### CODE REVIEW

**Comment by malemburg** [comment]
Hmm, I think it's useful to be able to see the job entry status as job reviewer, so would rather not like to merge this PR.

**Comment by malemburg** [comment]
Perhaps the wording in the info box could be changed to emphasize more on the status rather than way the entry is visible.

**Comment by frankwiles** [comment]
I agree @malemburg

**Comment by berkerpeksag** [comment]
@malemburg agreed. Do you have a suggestion for wording?

**Comment by Mariatta** [comment]
I'm not a maintainer, but wondering how many status is there for a job entry?
Is it just 'approved' and 'not approved'?
What do you think about displaying the job status as badge/label/tag instead of a box with many words, where all we care about is the status of it.

**Comment by malemburg** [comment]
On 16.09.2016 00:53, Mariatta wrote:

> I'm not a maintainer, but wondering how many status is there for a job entry?
> Is it just 'approved' and 'not approved'?

There are a few more states (see the job model admin page for all
of them).

> What do you think about displaying the job status as badge/label/tag instead of a box with many words, where all we care about is the status of it.

That would be nice to have. I guess the text box was simply easiest
to implement.

Removing this part from the text would likely be enough:

"You're able to see this because you're in the staff or super user group."

## 

Marc-Andre Lemburg
http://www.malemburg.com/

**Comment by berkerpeksag** [comment]
Marc-Andre's comment has been addressed in https://github.com/python/pythondotorg/pull/1012.

**Pull request closed without merging**
