### PR TITLE
Update pythondotorg.yml to work with newer Ansible

### LINKED ISSUE #1178: Vagrant up fails
MacOS 10.12.6
Vagrant: Installed Version: 1.9.7
Virtualbox: Version 5.1.24 r117012

I tried to run `vagrant up` from the latest master and it failed to create the database properly. 

Full log output: 

```
Levs-iMac:pythondotorg levlaz$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20171030.0.0'. The latest is version '20171030.0.1'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: pythondotorg_default_1509594353978_43981
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Available bridged network interfaces:
1) en1: Wi-Fi (AirPort)
2) en0: Ethernet
3) en2: Thunderbolt 1
4) en3: Thunderbolt 13
5) p2p0
6) awdl0
7) bridge0
==> default: When choosing an interface, it is usually the one that is
==> default: being used to connect to the internet.
    default: Which interface should the network bridge to? 1
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: bridged
==> default: Forwarding ports...
    default: 8000 (guest) => 8001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.36
    default: VirtualBox Version: 5.1
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /home/vagrant/pythondotorg => /Users/levlaz/git/pythondotorg
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and
make sure become_method is 'sudo' (default). This feature will be removed in
version 2.6. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
 [WARNING]: Ignoring invalid attribute: sudo

 [WARNING]: Ignoring invalid attribute: sudo_user


PLAY [Create a pythondotorg VM via Vagrant] ************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Run apt-get update] ******************************************************
changed: [default]

TASK [Install base packages] ***************************************************
changed: [default] => (item=[u'build-essential', u'libpq-dev', u'libxml2-dev', u'libxslt-dev', u'lib32z1-dev', u'git', u'python3', u'python3-dev', u'python-setuptools', u'python-pip', u'ruby'])

TASK [Install base Python packages] ********************************************
changed: [default]

TASK [Install python-lxml deps] ************************************************
changed: [default]

TASK [Install base Ruby packages] **********************************************
changed: [default]

TASK [Install PostgreSQL] ******************************************************
changed: [default] => (item=[u'postgresql', u'postgresql-contrib', u'libpq-dev', u'python-psycopg2'])

TASK [Ensure the PostgreSQL service is running] ********************************
ok: [default]

TASK [Ensure database is created] **********************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OperationalError: FATAL:Peer authentication failed for user "postgres"
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database: FATAL:  Peer authentication failed for user \"postgres\"\n"}
        to retry, use: --limit @/Users/levlaz/git/pythondotorg/provisioning/pythondotorg.retry

PLAY RECAP *********************************************************************
default                    : ok=8    changed=6    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### PR DESCRIPTION
**Pull request by berkerpeksag**
Fixes #1178

### CODE REVIEW

**Comment by levlaz** [comment]
@berkerpeksag thank you for working on this. Made it a bit closer but still seems to fail on my end: 

```
TASK [Install PostgreSQL] ******************************************************
changed: [default] => (item=[u'postgresql-9.5', u'postgresql-contrib-9.5', u'libpq-dev', u'python-psycopg2'])

TASK [Ensure the PostgreSQL service is running] ********************************
ok: [default]

TASK [Ensure database is created] **********************************************
changed: [default]

TASK [Ensure user has access to the database] **********************************
changed: [default]

TASK [Ensure python/pythondotorg is cloned] ************************************
ok: [default]

TASK [Install packages required by the Django app inside virtualenv] ***********
changed: [default]

TASK [Install packages required by Gemfile] ************************************
ok: [default]

TASK [Install database migrations] *********************************************
changed: [default]

TASK [Create a superuser for Django admin] *************************************
changed: [default]

RUNNING HANDLER [Restart PostgreSQL] *******************************************
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service postgresql: Failed to restart postgresql.service: Interactive authentication required.\nSee system logs and 'systemctl status postgresql.service' for details.\n"}
	to retry, use: --limit @/Users/levlaz/git/pythondotorg/provisioning/pythondotorg.retry

PLAY RECAP *********************************************************************
default                    : ok=15   changed=11   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by berkerpeksag** [comment]
@levlaz thanks for testing. Can you try again with e43ea257141fdad9410005ff1b1a362821f8a476?

**Comment by levlaz** [comment]
Thank you so much @berkerpeksag https://github.com/python/pythondotorg/commit/e43ea257141fdad9410005ff1b1a362821f8a476 works like a charm. 

I was able to run through the installation guide as documented and everything works 100%. :)

**Comment by berkerpeksag** [comment]
That's great! Could you also test with a fresh box? You probably need to run `vagrant destroy` and do `vagrant up --provision` again.

**Comment by levlaz** [comment]
@berkerpeksag just to confirm, doing a fresh install from the latest master worked as well. Thank you again.

**Pull request merged**
