### PR TITLE
Redirect legacy community page

### LINKED ISSUE #2294: File not found when looking for a python t-shirt
**Describe the bug**
When I visit the community tab of the python website, and then click on Python T-Shirts and other merchandise, I get file not found.

**To Reproduce**
1. Go to Community tab in the top bar of the website
2. Click on "Community"
3. Scroll down to [Python T-Shirts and other merchandise](https://www.python.org/community/merchandise/)

**Expected behavior**
Awesome t-shirts page to support the awesome Python software foundation.

### PR DESCRIPTION
**Pull request by dorian-adams**
Permanently redirect legacy community page, /community-landing/, to /community/.

Resolves #2294

### CODE REVIEW

**Review by eamanu — APPROVED** [review]
But IMO, this PR does not fix #2294 because python community merchandise is not found. https://www.python.org/community-landing/merchandise/

**Comment by dorian-adams** [comment]
Thank you @eamanu , I made a commit to address that. I switched to regex to catch all of the old URLs.

**Comment by brunohdmacedo** [comment]
❤️ 

> Obrigado ?eamanu , eu fiz um compromisso para resolver isso. Eu mudei para regex para pegar todos os URLs antigos.

**Comment by ewdurbin** [comment]
Just seeing this but doing the redirect in nginx is more efficient and where we retain most static/long-lived redirects: https://github.com/python/pythondotorg/blob/main/config/nginx.conf.erb

**Pull request merged**
