### PR TITLE
Update readme, clarify that this is not CPython's issue tracker

### PR DESCRIPTION
**Pull request by Mariatta**
We have people mistakenly reporting issues with CPython here.
Figured it will be good to explain that this is just for python.org, not CPython.

### CODE REVIEW

**Review by berkerpeksag — COMMENTED** [review]
Perhaps it would be better if we create an issue template? I doubt people would read the README before filing an issue here :)

**Comment by Mariatta** [comment]
Issue template sounds good too. Ok I'll try to come up with one.

**Comment by Mariatta** [comment]
Issue templates created in https://github.com/python/pythondotorg/pull/1296

I think having that info in readme is useful too though.

**Review by berkerpeksag — APPROVED** [review]

**Comment by berkerpeksag** [comment]
Thanks!

**Pull request merged**
