### PR TITLE
removed ..

### PR DESCRIPTION
**Pull request by aaditkapoor**

### CODE REVIEW

**Comment by benjaminp** [comment]
This doesn't seem correct. What were you trying to do?

**Comment by aaditkapoor** [comment]
Add some comments above the import statement.

**Comment by benjaminp** [comment]
What comment did you add? I don't see any in the diff.

**Comment by aaditkapoor** [comment]
Add a comment above the import statement, it is easy to understand.

On Sat, Sep 27, 2014 at 11:28 PM, Benjamin Peterson <
notifications@github.com> wrote:

> What comment did you add? I don't see any in the diff.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/pull/478#issuecomment-57060589.

## 

Thanks
Aadit Kapoor

**Comment by benjaminp** [comment]
I'm afraid I don't understand. This change is causing the build to fail. What are you trying to accomplish?

**Comment by aaditkapoor** [comment]
Code readability.

On Mon, Sep 29, 2014 at 9:50 AM, Benjamin Peterson <notifications@github.com

> wrote:
> 
> I'm afraid I don't understand. This change is causing the build to fail.
> What are you trying to accomplish?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/python/pythondotorg/pull/478#issuecomment-57115546.

## 

Thanks
Aadit Kapoor

**Comment by birkenfeld** [comment]
> Code readability.

This pull request looks completely unrelated to that; please check that it contains the correct commit(s).

**Pull request closed without merging**
