### PR TITLE
Bootstrap script for development on Windows

### PR DESCRIPTION
**Pull request by techtonik**
This installs all requirements and creates `manage.bat` to make activation/deactivation hassle limited.

### CODE REVIEW

**Comment by techtonik** [comment]
Oops. Need to remove one commit.

**Comment by berkerpeksag** [comment]
We are already using Ansible to bootstrap a development environment. Please do not invent your own. Manual installation steps are already documented at https://pythondotorg.readthedocs.org/install.html#manual-setup

**Comment by techtonik** [comment]
@berkerpeksag I am not satisfied with user experience of both your manual instructions and undocumented Ansible workflow. Can we reopen this and bring more opinions into the discussion?

**Comment by malemburg** [comment]
I'm with Berker here: we've moved to Ansible from a Chef based approach. We don't need a separate home grown approach in the official repo. You are free to host this by yourself, of course.

**Comment by techtonik** [comment]
@malemburg I know something about both Chef and Ansible, and I still think that such scripts are needed, because the audience for them is different. It is for occasional contributors, who just need a fast way to setup things - to test one shot patch before submitting design fixes. If you want to test how it works, get yourself a timer and ask someone to show you python.org website running locally. This scripts saves about 2-30 minutes.

**Pull request closed without merging**
