### PR TITLE
Add donate button to header

### PR DESCRIPTION
**Pull request by nlhkabu**
Adds donation button to header.

TODO:

- [x] Add a destination to the link.  @bwaliszewski could you tell me - where would you like the button to link to?

## Desktop
screenshot from 2018-12-01 14-37-47

## Tablet
screenshot from 2018-12-01 14-37-37

## Mobile
screenshot from 2018-12-01 19-13-21

Note @bwaliszewski - I didn't change the color of the other button as we discussed, because I realised that yellow buttons are being used in the header on several of the other internal pages.

### CODE REVIEW

**Comment by bwaliszewski** [comment]
I like the locations you're showing, Nicole. Let's go for it.

**Comment by nlhkabu** [comment]
Thanks @bwaliszewski.  Could you tell me, where do you want the user to go when they click on the link?

**Comment by bwaliszewski** [comment]
Please have the button link to https://www.python.org/psf/donations/. thanks.

**Comment by nlhkabu** [comment]
Updated. @ewdurbin would you be able to review and merge this PR?  If not, could you indicate who can/should?  Thanks :sparkles:

**Review by ewdurbin — APPROVED** [review]

**Comment by ewdurbin** [comment]
This required a bit of work to cherry-pick onto `release`, but it is out there.

Unfortunately our CSS isn't cache busted, so you may need to dump your browser cache to apply the style 😓

**Pull request merged**
