### PR TITLE
(issue #93) Fix the position of the blog time/date in /blogs

### PR DESCRIPTION
**Pull request by luanfonceca**
Adding `position: relative` and `top: 30px` to the `<time>` element inside a `.date-posted`.

### CODE REVIEW

**Comment by birkenfeld** [comment]
What is a revert of de3f656 doing in there?

Also whitespace cleanup should be in a separate commit.

**Comment by luanfonceca** [comment]
ohhh, i really sorry for that, i did that "revert" trying to fix a commit that i did wrong in my fork... And all the commits, in the same branch are linked to the pull-request :(

Can you just reject that and I do it right after? 
Without these spaces that the Sublime Text removes and inside a specific branch... In the right way.

Sorry for that again.

**Comment by birkenfeld** [comment]
OK, I'll close this one. If you do the next request from a different branch, it's easier to update with a forced branch-push.

**Comment by luanfonceca** [comment]
Yeah, i will. Thanks so much.

**Pull request closed without merging**
