### PR TITLE
Fixed an off canvas problem with the right: -9999px menu elements.

### PR DESCRIPTION
**Pull request by jhogue**
But the larger issue is that navigation for touch devices is pretty terrible. Gotta come up with a better UI pattern to address touch for a complicated multi-tier navigation like this one.

Signed-off-by: J. Hogue j@projectevolution.com

### CODE REVIEW

**Comment by frankwiles** [comment]
Same with this one, I keep getting merge conflicts in the CSS and SASS that I'm scared to touch! :)

**Comment by jhogue** [comment]
This shouldn't have any merge conflicts on it anymore, now that the previous PR has been reviewed.

**Comment by frankwiles** [comment]
Same on this one, just go ahead and make master happy! :)

**Comment by jhogue** [comment]
Ah... thought I dealt with all this. Lemme try again tomorrow morning.

On Wed, Jul 24, 2013 at 3:51 PM, Frank Wiles notifications@github.comwrote:

> Same on this one, just go ahead and make master happy! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/proevo/pythondotorg/pull/30#issuecomment-21511308
> .

## 

_J. Hogue_: Design Director at Project Evolution
t: 888.456.0467 | c: 401.831.1963

**Comment by frankwiles** [comment]
No worries, thanks!

## 

Frank Wiles
Revolution Systems | http://www.revsys.com/
frank@revsys.com   | (800) 647-6298

**Comment by jhogue** [comment]
I'm very disappointed with the way this all worked out. I think I lost work
in the process here, and I'm not sure where it went. I bet I can find it in
Git somewhere.

Please merge this with master and let me know. I'll pull it all down again
and try to get that touch navigation pattern back. It got all screwed up
and I'm sure it was my fault somehow.

On Wed, Jul 24, 2013 at 4:19 PM, Frank Wiles notifications@github.comwrote:

> No worries, thanks!
> 
> ## 
> 
> Frank Wiles
> Revolution Systems | http://www.revsys.com/
> frank@revsys.com | (800) 647-6298
> 
> On Wed, Jul 24, 2013 at 3:15 PM, J. Hogue notifications@github.com
> wrote:
> 
> > Ah... thought I dealt with all this. Lemme try again tomorrow morning.
> > 
> > On Wed, Jul 24, 2013 at 3:51 PM, Frank Wiles notifications@github.comwrote:
> > 
> > > Same on this one, just go ahead and make master happy! :)
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/proevo/pythondotorg/pull/30#issuecomment-21511308>
> > > .
> > 
> > ## 
> > 
> > _J. Hogue_: Design Director at Project Evolution
> > t: 888.456.0467 | c: 401.831.1963
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/proevo/pythondotorg/pull/30#issuecomment-21512747>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/proevo/pythondotorg/pull/30#issuecomment-21513023
> .

## 

_J. Hogue_: Design Director at Project Evolution
t: 888.456.0467 | c: 401.831.1963

**Pull request merged**
