### PR TITLE
configure cmarkgfm to make cms pages more flexible

### LINKED ISSUE #2181: Add a "Markdown with HTML" option to the CMS pages
The current CMS uses https://pypi.org/project/cmarkgfm/ for rendering Markdown syntax when selecting "Markdown" in the CMS.

This defaults to safe rendering of the given Markdown, which is fine. However, in some cases, it may be useful to e.g. make use of the available JQuery UI support for showing more advanced widgets such as accordions.

For the PSF Trademark FAQ page, it would be useful to have an option to add the needed raw HTML directly to the Markdown content (unless there's some other way to get this working): https://www.python.org/psf/trademarks-faq/ The page is becoming rather long and an accordion would help make navigation easier.

Adding support should be easy: simply add another tuple to https://github.com/python/pythondotorg/blob/main/pages/models.py#L51 using a lamdba to enable the `cmarkgfm.cmark.CMARK_OPT_UNSAFE` option. I can give this a try, if there's a chance to get this accepted.

### PR DESCRIPTION
**Pull request by ewdurbin**
closes #2181

### CODE REVIEW

**Comment by malemburg** [comment]
Looks good, but this will enable unsafe markdown on all pages. Do you think that's a good idea ?

My idea was to only add this as an extra option in the CMS.

**Comment by ewdurbin** [comment]
Fair point. Updated.

**Review by malemburg — APPROVED** [review]
LGTM. Editors of CMS pages will know what the risks are, I suppose, so perhaps a new option is not needed.

**Review by malemburg — APPROVED** [review]
Ok, this is even better. Thanks :-)

**Comment by malemburg** [comment]
Thanks for implementing this, Ee.

How long will we have to wait before this goes live ?

**Comment by ewdurbin** [comment]
looks like you were able to test it in staging based on issue discussion, it won't go to prod until its merged into the `release` branch, but seems you may have more to look into.

**Pull request merged**
