### PR TITLE
Fix issue 883

### PR DESCRIPTION
**Pull request by CianciuStyles**
Hello, sorry for giving you any update on this, it took me longer than I had originally thought.

Anyway, I tried to apply the least changes to fix the misbehaviour, but there's still room for improvements, at a cost of some larger changes in the code (e.g., move the <time> tag in the /events/ page, so to make it not use absolute positioning to show it on the left).

Let me know if there still are some changes to be made. Cheers!

### CODE REVIEW

**Comment by berkerpeksag** [comment]
No problem, thanks for the PR! :) I will take a look at it this weekend.

**Comment by CianciuStyles** [comment]
Hello, any update about this PR?

**Comment by berkerpeksag** [comment]
Oops, sorry about that :( Please ping me again if I don't review/merge this by Saturday.

**Comment by berkerpeksag** [comment]
Merged in https://github.com/python/pythondotorg/commit/a1658e9cd56d3d745647434e27a1e231f6fc0473, thanks! I hope you will continue to send high quality pull requests like this :)

**Comment by berkerpeksag** [comment]
(I will test this on https://staging.python.org/ for a while then deploy it to production.)

**Pull request closed without merging**
