### PR TITLE
Fixes #1658 Version gating does not handle 3.10 and later

### LINKED ISSUE #1658: Version gating for #1655 does not handle Python 3.10, 3.11, ... etc
See discussion on #1655, the implementation was merged without addressing lexical/numerical sorting in order to accommodate the release of Python 3.9

### PR DESCRIPTION
**Pull request by zooba**

### CODE REVIEW

**Comment by zooba** [comment]
Trusting to CI to check this one - I haven't set up a local environment yet.

**Comment by zooba** [comment]
I had a feeling I couldn't just call the function there... :(

**Comment by zooba** [comment]
Sorry, forgot about this, but looks like my last change worked?

Not sure who is best for reviewing/merging PRs in this repo... @ewdurbin is it you?

**Comment by zooba** [comment]
Ping on this again. This is going to matter for when 3.10 final is released. (@ambv do you have power over this repo now?)

**Review by ewdurbin — APPROVED** [review]

**Pull request merged**
