### PR TITLE
fix bug number #531

### PR DESCRIPTION
**Pull request by nirgn975**
# Fix bug #531

**Bug:** the website jump to the nav when initiate scrolling, only on mobile.
**Solution:**
- remove the `scroll_fired = false` that made the jump from the js file.
- edit the css file so that the nav will be hidden when page load.
- edit the js file so clicking on "The Python Network" button will open the nav, and clicking on "Close" button will close the nav.

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Great, thanks! :)

Can you also commit the changes in static/sass/style.scss? It would be nice to avoid making whitespace changes, by the way.

**Comment by nirgn975** [comment]
Of course, I did another commit to the branch.
I avoid whitespace (from the original files), clean up the changes I made (to be minimalist from line numbers perspective), and commit the changes in style.scss too.

Should I do another pull request?

**Comment by berkerpeksag** [comment]
> Should I do another pull request?

No, this looks good. I'll take a look at the patch this weekend. Thanks again!

**Comment by berkerpeksag** [comment]
Sorry for my late response. I've just played with this and looks good to me in general. I will test with different browsers tomorrow.

**Comment by berkerpeksag** [comment]
By the way, can we keep the current animation? Also, the height of the "close" bar looks a bit lower on Firefox.

**Comment by nirgn975** [comment]
I fixed the "close" bar, and create the slide animation.
It's works good, but there is href to "python-network" on the "close" bar that I couldn't delete, so when I press the "close" bar it jumping to "The Python Network" and then do the animation and that causing the page to slide down more then it should. So, I need some help in deleting the "href" on "close-python-network".

**Comment by berkerpeksag** [comment]
To be honest, that JS file is a bit cryptic and contains many dead/unreachable/out-dated code. I used a slightly different approach and played with it in the last ~2 hours. Will merge it soon(tm) :)

**Comment by berkerpeksag** [comment]
Merged in https://github.com/python/pythondotorg/commit/ddf71c63c24714abadcffed188f3a8eae342320d. Thanks @nirgn975!

**Pull request closed without merging**
