### PR TITLE
[WIP] started adding django 3.2 support

### PR DESCRIPTION
**Pull request by auvipy**
some packages like Django-pipeline lack Django 2.2 support. Will address them one by one.

### CODE REVIEW

**Review by berkerpeksag — CHANGES_REQUESTED** [review]
We shouldn't upgrade from 2.0 to 2.2. The proper way to do this is upgrade to 2.1 first. And I'd suggest to create a some sort of plan before starting to work on this. For example, why django-pipeline doesn't work with Django 2.2? What's the action plan? Add Django 2.2 support to django-pipeline? Or use something else?

**Comment by auvipy** [comment]
https://github.com/jazzband/django-pipeline/pull/693

**Comment by auvipy** [comment]
thanks for your input. Some of them are certainly valid. on the 2.0-2.1 upgrade, it's really not necessary as Django LTS to LTS upgrade is much easier than before. So I would like to stand on the ground of django 2.0 to 2.2 upgrade. definitely with proper plans and rigorous testing.

**Comment by auvipy** [comment]
django-pipeline is now on @jazzbrand/django-pipeline so I am free to contribute and release. Regarding using something else rather than django-pipeline I am open to looking for more options.

**Comment by berkerpeksag** [comment]
Sorry, I'm not going to merge a PR that attempts to upgrade Django from X to X+2 directly. Django release notes aren't cover all behavior changes, so it's much easier to detect regressions since the scope of the changes are much smaller between X and X+1.

**Comment by auvipy** [comment]
I am not accepting to get this PR merged anytime soon. As It's natural to complete many things which need to be addressed first. I can start another pr with X to X+1 upgrade. I do also want to experience your concerns are up to date.

**Comment by auvipy** [comment]
re_path or new simpler regex free URL paths which one do you prefer for this project?

**Comment by auvipy** [comment]
used both

**Comment by hugovk** [comment]
Closed because https://github.com/python/pythondotorg/pull/2520 has upgraded to 4.2. Thanks anyway!

**Pull request closed without merging**
