### PR TITLE
Added Author, Release, and Version to EPUB build via Makefile

### PR DESCRIPTION
**Pull request by cclauss**
http://bugs.python.org/issue20969

### CODE REVIEW

**Comment by benjaminp** [comment]
You know this Makefile doesn't affect the Python docs, right?

**Comment by cclauss** [comment]
Sorry...  I am just learning.  I thought it did.  Please reject my pull requests.

**Comment by cclauss** [comment]
If you could please provide me a URL to the right repo, I could try again.

**Comment by benjaminp** [comment]
hg.python.org/cpython Please also use the CPython tracker you linked to above for submitting patches.

**Pull request closed without merging**
