### PR TITLE
don't denote old versions as 'the newest major release of Python'

### PR DESCRIPTION
**Pull request by erlend-aasland**
See also python/cpython#105844

### CODE REVIEW

**Comment by erlend-aasland** [comment]
I was unable to find out where the _"is the newest major release of the Python programming language"_ string for 3.11.x was located (but I did not devote much time for the investigation either ...):

https://www.python.org/downloads/release/python-3114/

For 3.11.4, it is true that it's the newest major release of Python, but that's not true for 3.11.3 and older. Perhaps "the newest stable release of Python" is more accurate.

**Comment by erlend-aasland** [comment]
(I reverted 252ddbdd81fcae970dacbab7a7a9218996ceb1e3 as it broke CI, and I have no time to investigate that)

**Comment by jamestwebber** [comment]
> I was unable to find out where the _"is the newest major release of the Python programming language"_ string for 3.11.x was located (but I did not devote much time for the investigation either ...):

It seems like these are only present in the `fixtures/downloads.json` file, which I think means it is stored in the database as markdown and just gets rendered in its entirety? So possibly someone (the release manager?) is writing this by hand (or has a template they use for it)

**Comment by erlend-aasland** [comment]
Yep, makes sense.

**Comment by ewdurbin** [comment]
The changes here are for the fixtures. The contents itself is managed in the CMS in the live database.

Happy to merge, but it will have no impact on the live pages at python.org. Someone from @python/python-release-managers will need to update the existing CMS contents.

**Comment by erlend-aasland** [comment]
If it has no impact, there's no need to merge :) Thanks for the info!

**Comment by jamestwebber** [comment]
The change to `docs/source/administration.rst` is still relevant, yes? It's a tiny point but perhaps would help nudge future announcements to use precise wording.

**Pull request closed without merging**
